### ISSUE TITLE
[UI] Make a dropdown list near the select field (password/mnemonic)

### ISSUE THREAD

**Issue by Bastien-Satochip** [Toporin/Seedkeeper-iOS#13]
Currently, when I click on the "Type of secret", there is a huge purple menu that pops out to only present 2 lines...
Is it possible to update the UI to make it displayed as a drop down list or similar?

![photo_5769534469454283661_y](https://github.com/Toporin/Seedkeeper-iOS/assets/87421384/f7a115ec-de1d-4040-ac10-3e62e12c2f8b)

The text can also be updated with a capital letter to start the word.

**Comment by lioDLV** [comment]
As there is no "dropdown" component for swiftUI, my suggestion would be to :
- Reduce the sheet height
- Re-style the background with blur thin material from Apple

Result :
![IMG_9408](https://github.com/Toporin/Seedkeeper-iOS/assets/36716936/e97917ef-26ff-445c-bb06-bc2e25770064)
