### ISSUE TITLE
[UI] Intro screens update + issue on the start button

### ISSUE THREAD

**Issue by Bastien-Satochip** [Toporin/Seedkeeper-iOS#2]
Model: iPhone 13 pro
OS: 16.1.1

For each "Intro screens", there is a issue on the bottom of the screen. See the white border.
![photo_5769534469454283569_y](https://github.com/Toporin/Seedkeeper-iOS/assets/87421384/a6b45a1e-42bb-46d9-a219-12e1e262ae2a)

For the first screen, could you change the title from "welcome" to "Welcome" with a capital W.
![photo_5769534469454283569_y](https://github.com/Toporin/Seedkeeper-iOS/assets/87421384/c5023c81-1ed5-4a2a-9b27-683f68fe637c)

For the last screen, could you add a green button (see Figma):
val SatoGreen = Color(0xFF25B59A
Title_EN: Watch video tutorial
Link_EN: https://www.youtube.com/watch?v=-H7z7_RuDJw

Title_FR: Voir le tutoriel
Link_FR: https://www.youtube.com/watch?v=HqKNE1hkc9A

And regarding this last screen, could you change the "start" button from "start" to "Start" with a capital S?
This button is currently NOT working on my iPhone. I can go on the homescreen when I press it.
![photo_5769534469454283570_y](https://github.com/Toporin/Seedkeeper-iOS/assets/87421384/7f824ceb-0083-4df9-8f8d-5c763895e8be)

As the image is cropped (on my phone), you can download the full one here:
![Seedkeeper - Mobile App - NFC 1](https://github.com/Toporin/Seedkeeper-iOS/assets/87421384/c5d78eab-e077-4b8d-a22e-c2520618fa9d)

**Comment by lioDLV** [comment]
We need to find some kind of hack solutions because of how swiftUI handle this kind of "Tabs" presentation => Might need to explain in more details

**Comment by Bastien-Satochip** [comment]
Tested and ok.
