### ISSUE TITLE
[Improvment] Backup process

### ISSUE THREAD

**Issue by Bastien-Satochip** [Toporin/Seedkeeper-iOS#31]
The backup process is currently looking like that:

https://github.com/user-attachments/assets/c43966dc-33aa-45e0-82bd-4e5fd89619e3

Process:
- I scan my (main) Seedkeeper
- Provide the PIN code
- Go to Settings and click on "Backup"

- First screens explain how it will work
- I click on "Start"
- Wizard tells me to prepare the backup card, I click on Next
- I scan my backup card.

First problem: pay a closer look at the background screen that went from the "prepare your backup card" screen to the very first one that explain how to process works.
The screen showed in the background:
![image](https://github.com/user-attachments/assets/f3d8b2fb-e729-46da-af61-391f0977d102)
But it should be this screen:
![image](https://github.com/user-attachments/assets/92d06c92-244c-4b74-acb7-0285c29ec9a1)

Here, my backup card is not initialized. So I have to put a new PIN code.
I do it, twice. But then, the backup process goes back to the first step.

Normally it should continue the process. So the next screen should have been: "Your backup card is now paired", "Scan your Seedkeeper (master) to initiate the backup".

We should therefore arrive on this screen: 
![image](https://github.com/user-attachments/assets/bcebf575-7cd2-4333-a257-df35c488c74b)
In fact, the illustration pictogram here should be as follows: 
![image](https://github.com/user-attachments/assets/96946bca-98df-4270-afa9-f55896655350)

For the rest, it's OK.

Please also pay attention to the French translations... There are a few mistakes and some NFC toast that are in still in English. 
Some button might also be renamed not to be cropped like this one:
![image](https://github.com/user-attachments/assets/af7683f8-7be6-4c47-ba61-4633853e7356)

You could change the title to "Scanner".

**Comment by Toporin** [comment]
See also https://github.com/Toporin/Seedkeeper-iOS/issues/51
