### ISSUE TITLE
[Improvment] Add a search bar when there are a lot of records

### ISSUE THREAD

**Issue by Bastien-Satochip** [Toporin/Seedkeeper-iOS#32]
Please, add a search field on top of the main page when there are too many records to display.

![image](https://github.com/user-attachments/assets/da1e50eb-314f-4d8b-a3d0-f8e1eec657a5)

This search field should be displayed when: 
- there are more than X entries (advice me on the X, I suppose it depends on the phone screen size).
- the search is done on the label name.

The "+" add button should always be on top.

And please add a filter so the user can sort the search on a specific type of password:
- mnemonic 
- password

(This filter list might evolve in a near future).

**Comment by Toporin** [comment]
The search and filter functionality is not intuitive:

If nothing is provided in the search field (field empty), the filter does not work: every secrets are shown, even if I select "mnemonic". User should be able to filter secrets by type only (without text filter).

If some chars are provided in the search field, the filter is applied correctly.

Also, when the filter is activated, no feedback is provided to user to show which secret type is filtered. I suggest to put a 'v' or other marking in front of the secret type selected in the filter dropdown list to show which type is selected (see image below). Another feedback can also be provided, such as showing the selected type in bold...

![photo_5868321822523638502_y](https://github.com/user-attachments/assets/4d1a32c1-87d3-46bc-a833-b303ed406fb4)
![photo_5868321822523638503_y](https://github.com/user-attachments/assets/fbdbbc31-c858-4054-a25d-aa514a577223)

**Comment by Bastien-Satochip** [comment]
Tested and fixed.
