### ISSUE TITLE
[Improvment] Automatically refresh the secret list with the newly created secret

### ISSUE THREAD

**Issue by Bastien-Satochip** [Toporin/Seedkeeper-iOS#42]
When creating a new secret and clicking the "Home" button, the user faced an "empty" list of secrets.
The newly created secret do not appear and the user had to refresh the list to see the new secret.

Is it possible to automatically refresh the view to list the newly created secret?

See the video for a better overview. I had to refresh at the very last step to see my newly created password.

https://github.com/user-attachments/assets/653a9d31-f95c-42e5-a864-1c7118b2c18b

**Comment by Toporin** [comment]
When a secret is created, it is automatically added to the list of secret shown in main menu, however, when selecting this secret in the list , then clicking on 'show' button does not show the correct secret!!
