### ISSUE TITLE
[UI-Update] Change the green color of the Genuine status

### ISSUE THREAD

**Issue by Bastien-Satochip** [Toporin/Seedkeeper-iOS#45]
The green color of the genuine status is too green. 
For a better UI, please update it...

From this code: #64FFC6

![Sans titre](https://github.com/user-attachments/assets/8b8bd031-8335-48c3-9464-e0b0f2e53e12)

To this code: #24B59B

![image](https://github.com/user-attachments/assets/9e012113-7d93-49a2-8cfb-6ae2d86b68f3)

The same for the Satochip logo on the top left home screen.

**Comment by Toporin** [comment]
Could you also change the colour of the 2 buttons 'Show card certificate' and 'Show sub-ca certificate' as well as the frame to same green when card is authentic (leave red if not authentic of course)?

![Screenshot 2024-08-02 at 21 19 43](https://github.com/user-attachments/assets/6e7df6fc-3976-4ef6-81bf-6bd1c1dd9cf6)
