### ISSUE TITLE
Check card authentikey before any sensitive operation

### ISSUE THREAD

**Issue by Toporin** [Toporin/Seedkeeper-iOS#52]
When performing an operation on the card (such as exporting/importing/resetting/showing... a secret), the app should check that the card being scanned for operation is the same card that was used for listing secrets. 

Otherwise, one might perform operations on a different card!

For reference, this is already done on the Satodime app, see for example [here](https://github.com/Toporin/Satodime-iOS/blob/a15b716274dc9603816640b81eb93892cf9b60c8/Satodime/Models/CardState.swift#L293)

**Comment by Bastien-Satochip** [comment]
Looks OK.

**Comment by Toporin** [comment]
Done in https://github.com/Toporin/Satodime-iOS/commit/0cdcd09dbae2dee03e6ef76979c698568cc6450d
