### ISSUE TITLE
Allow user to generate a secret multiple secrets before importing one

### ISSUE THREAD

**Issue by Toporin** [Toporin/Seedkeeper-iOS#54]
When generating a random password, a user may want to generate multiple candidates before selecting one that suits him better. 
Therefore, it is better to have 2 buttons on the bottom of the screen:
* A 'generate' button to generate a new random secret **each time** it is clicked
* the import button to import secret once all required inputs are validated

For illustration:
![photo_5868321822523638465_y](https://github.com/user-attachments/assets/fb4a89ba-8e8b-4eca-9a3b-c24f0fb3fe82)

**Comment by Bastien-Satochip** [comment]
Partially fixed. 
I close the issue and open a new one to explain the bug.

**Comment by Bastien-Satochip** [comment]
Looks OK but check #67

**Comment by Toporin** [comment]
Done in https://github.com/Toporin/Satodime-iOS/commit/0cdcd09dbae2dee03e6ef76979c698568cc6450d
