### ISSUE TITLE
When scanning a card, the app do not always ask for a PIN code

### ISSUE THREAD

**Issue by Toporin** [Toporin/Seedkeeper-iOS#56]
When I scan a card A, then another card B, the app does not ask for PIN for the second card and use the same PIN for both.
If the PIN for card B is different, the app will use a wrong PIN, thus generating an error and decreasing the card's PIN tries.

Solution: always ask PIN when scanning a card (except if the authentikey match previous card)

**Comment by Bastien-Satochip** [comment]
Looks OK.

**Comment by Toporin** [comment]
Done in https://github.com/Toporin/Satodime-iOS/commit/0cdcd09dbae2dee03e6ef76979c698568cc6450d
