### ISSUE TITLE
NFC scan toast for card setup

### ISSUE THREAD

**Issue by Toporin** [Toporin/Seedkeeper-iOS#57]
Message to user is missing when scanning a card that needs setup:

![photo_5868321822523638493_y](https://github.com/user-attachments/assets/b676d1ea-9222-4fcb-967b-67adbff94ca5)

**Comment by Bastien-Satochip** [comment]
Tested ad fixed.

**Comment by Toporin** [comment]
Done in https://github.com/Toporin/Satodime-iOS/commit/0cdcd09dbae2dee03e6ef76979c698568cc6450d
