### ISSUE TITLE
Disable autocorrect in label fields

### ISSUE THREAD

**Issue by Toporin** [Toporin/Seedkeeper-iOS#58]
And maybe in other fields if needed

**Comment by Bastien-Satochip** [comment]
Looks OK.

**Comment by Bastien-Satochip** [comment]
Ok, solved in Testflight v0.1.2 (2)

**Comment by Toporin** [comment]
Done in https://github.com/Toporin/Satodime-iOS/commit/0cdcd09dbae2dee03e6ef76979c698568cc6450d
