### ISSUE TITLE
[BUG] When I click on "Show logs" in the Settings page, the app crashes

### ISSUE THREAD

**Issue by Bastien-Satochip** [Toporin/Seedkeeper-iOS#7]
Model: iPhone 13 pro
OS: 16.1.1

When I click on "Show logs" in the Settings page, the app crashes.
Whenever I have scanned a card or not.

**Comment by lioDLV** [comment]
Fixed in commit d71f8e823e70f75f7d267422718332717aa31a73, waiting for validation
