### ISSUE TITLE
[UI] Can we change the toast logo when the PIN is required?

### ISSUE THREAD

**Issue by Bastien-Satochip** [Toporin/Seedkeeper-iOS#9]
When the user has to enter the PIN code, the big red exclamation mark ! makes me feel like there is an issue. 
And in fact, I just have to put my PIN code to unlock the card. 

Can we change this big red excalmation mark? 

![photo_5769534469454283584_y](https://github.com/Toporin/Seedkeeper-iOS/assets/87421384/fadac2c1-c310-45ff-90cb-1bc2ef5c6df4)

**Comment by lioDLV** [comment]
We can use the "V" icon, should I change it ?
